### ISSUE TITLE
Cannot read property 'resolveFolderFromPath' of undefined

### ISSUE THREAD

**Issue by ealves-pt** [jsreport/jsreport-child-templates#6]
Since I've updated to jsreport@2.2.0 I've been having the following issue:

```
TypeError: Cannot read property 'resolveFolderFromPath' of undefined
    at convert (/home/ea/jsreport/node_modules/jsreport-child-templates/lib/childTemplates.js:93:43)
    at asyncReplace (/home/ea/jsreport/node_modules/jsreport-child-templates/lib/childTemplates.js:162:51)
    at /home/ea/jsreport/node_modules/async-replace/async-replace.js:63:26
    at /home/ea/jsreport/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/home/ea/jsreport/node_modules/async/lib/async.js:233:13)
    at _parallel (/home/ea/jsreport/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/home/ea/jsreport/node_modules/async/lib/async.js:731:9)
    at module.exports (/home/ea/jsreport/node_modules/async-replace/async-replace.js:71:11)
    at tryCatcher (/home/ea/jsreport/node_modules/jsreport-child-templates/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/home/ea/jsreport/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at evaluateChildTemplates (/home/ea/jsreport/node_modules/jsreport-child-templates/lib/childTemplates.js:161:24)
    at Object.reporter.beforeRenderListeners.add (/home/ea/jsreport/node_modules/jsreport-child-templates/lib/childTemplates.js:180:12)
    at /home/ea/jsreport/node_modules/listener-collection/lib/listenerCollection.js:171:33
    at /home/ea/jsreport/node_modules/listener-collection/lib/listenerCollection.js:151:16
    at tryCatcher (/home/ea/jsreport/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ea/jsreport/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ea/jsreport/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ea/jsreport/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ea/jsreport/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ea/jsreport/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ea/jsreport/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ea/jsreport/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

Any idea on how to fix this?

**Comment by bjrmatos** [comment]
i just installed 2.2.0 and there is no issue related to this error message, so what i guess is that you have listed `jsreport-child-templates` explicitly in your package.json and you have updated it too, go back and install `jsreport-child-templates` version `1.0.0`, the latest version of `jsreport-child-templates` (which is `1.1.0`) is designed to work with a new feature of jsreport that is not released yet, so trying to use `jsreport-child-templates` `1.1.0` with jsreport `2.2.0` will not work

**Comment by ealves-pt** [comment]
That is correct. I just went back to `1.0.0` and it's working. Thank you for the feedback. :+1:
